Added compute_gene_scores nftest and standardized format of module
nf-core/nanostring pull request #101
Opened 2024-11-19 18:40 UTC by nschcolnicov

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/nanostring/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/nanostring _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-11-19 18:54 UTC, atrigila requested changes

2024-11-19 18:54 UTC, atrigila commented on conf/test_scores.config
> +    input           = 'https://raw.githubusercontent.com/nf-core/test-datasets/nanostring/samplesheets/samplesheet_test.csv'
You can add the same `params.pipelines_testdata_base_path`  here, like you did in the line after this one.

2024-11-19 18:54 UTC, atrigila commented on modules/local/compute_gene_scores/environment.yml
> +  - defaults
defaults channel should be removed from the `environment.yml`.

See:
https://github.com/nf-core/modules/issues/5829

2024-11-19 18:54 UTC, atrigila commented on modules/local/compute_gene_scores/environment.yml
> +name: compute_gene_scores
name is also removed in the new nf-core `environment.yml` specification convention.

2024-11-19 18:54 UTC, atrigila commented on modules/local/compute_gene_scores/main.nf
> -    conda "r-yaml=2.3.7 r-ggplot2=3.4.4 r-dplyr=1.1.4 r-stringr=1.5.0 bioconductor-gsva=1.46.0 bioconductor-singscore=1.18.0 r-factominer=2.8.0 r-tibble=3.2.1 r-matrixstats=1.1.0"
You removed conda but you didn't add the `environment.yml`

2024-11-19 18:54 UTC, atrigila commented on modules/local/compute_gene_scores/main.nf
> -    conda "r-yaml=2.3.7 r-ggplot2=3.4.4 r-dplyr=1.1.4 r-stringr=1.5.0 bioconductor-gsva=1.46.0 bioconductor-singscore=1.18.0 r-factominer=2.8.0 r-tibble=3.2.1 r-matrixstats=1.1.0"
Please also test the nf-test with `--profile conda`

2024-11-19 19:36 UTC, nschcolnicov commented on modules/local/compute_gene_scores/main.nf
> -    conda "r-yaml=2.3.7 r-ggplot2=3.4.4 r-dplyr=1.1.4 r-stringr=1.5.0 bioconductor-gsva=1.46.0 bioconductor-singscore=1.18.0 r-factominer=2.8.0 r-tibble=3.2.1 r-matrixstats=1.1.0"
I also tested with conda, and it worked for some reason, I'll update this

2024-11-20 12:28 UTC, atrigila approved these changes

2024-11-20 14:17 UTC, merged