Release 1.2.1
nf-core/nanostring pull request #59
Opened 2024-01-17 15:41 UTC by apeltzer

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/nanostring/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/nanostring _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-01-17 15:49 UTC, apeltzer commented on CHANGELOG.md
> +## v1.2.1 - 2024-xx-xx - Nanometre
```suggestion
## v1.2.1 - 2024-01-18 - Nanometre
```

2024-01-18 07:59 UTC, christopher-mohr requested changes
Found a couple of minor things

2024-01-18 07:59 UTC, christopher-mohr commented on .devcontainer/devcontainer.json
> +                "python.linting.pylintPath": "/opt/conda/bin/pylint",
I still think these trailing commas are wrong ;)

```suggestion
                "python.linting.pylintPath": "/opt/conda/bin/pylint"
```

2024-01-18 07:59 UTC, christopher-mohr commented on .devcontainer/devcontainer.json
> +            "extensions": ["ms-python.python", "ms-python.vscode-pylance", "nf-core.nf-core-extensionpack"],
```suggestion
            "extensions": ["ms-python.python", "ms-python.vscode-pylance", "nf-core.nf-core-extensionpack"]
```

2024-01-18 07:59 UTC, christopher-mohr commented on CHANGELOG.md
> +- Added the Bioinformatics publication to the citation list
```suggestion
- [#55](https://github.com/nf-core/nanostring/pull/55) - Added the Bioinformatics publication to the citation list
```

2024-01-18 07:59 UTC, christopher-mohr commented on CHANGELOG.md
> +- Updated to nf-core template 2.11.1
```suggestion
- [#55](https://github.com/nf-core/nanostring/pull/55) - Updated to nf-core template 2.11.1
```

2024-01-18 07:59 UTC, christopher-mohr commented on CHANGELOG.md
> +- Granularized the containers for NACHO and Heatmaps
```suggestion
- [#58](https://github.com/nf-core/nanostring/pull/58) - Granularized the containers for NACHO and Heatmaps
```

2024-01-18 07:59 UTC, christopher-mohr commented on lib/WorkflowNanostring.groovy
>                  "<li>Ewels, P., Magnusson, M., Lundin, S., & Käller, M. (2016). MultiQC: summarize analysis results for multiple tools and samples in a single report. Bioinformatics , 32(19), 3047–30
Also add the Nacho paper here?

2024-01-18 07:59 UTC, christopher-mohr commented on modules.json
> +                        "git_sha": "8ec825f465b9c17f9d83000022995b4f7de6fe93",
I guess this should not be the same checksum

2024-01-18 08:01 UTC, apeltzer commented on .devcontainer/devcontainer.json
> +                "python.linting.pylintPath": "/opt/conda/bin/pylint",
Unfortunately not, this was discussed yesterday on Slack :)

2024-01-18 08:01 UTC, apeltzer commented on .devcontainer/devcontainer.json
> +            "extensions": ["ms-python.python", "ms-python.vscode-pylance", "nf-core.nf-core-extensionpack"],
Same here :)

2024-01-18 08:06 UTC, apeltzer commented on lib/WorkflowNanostring.groovy
>                  "<li>Ewels, P., Magnusson, M., Lundin, S., & Käller, M. (2016). MultiQC: summarize analysis results for multiple tools and samples in a single report. Bioinformatics , 32(19), 3047–30
```suggestion
                "<li>Ewels, P., Magnusson, M., Lundin, S., & Käller, M. (2016). MultiQC: summarize analysis results for multiple tools and samples in a single report. Bioinformatics , 32(19), 3047–3048. doi: /10.1093/bioinformatics/btw354</li>,
                 "<li>Canouil, M. et al. NACHO: a Nanostring nCounter data QC package. Bioinformatics (2019) doi:10.1093/bioinformatics/btz647.
  </li>"
```

2024-01-18 08:10 UTC, apeltzer commented
@nf-core-bot pretty please fix linting

2024-01-18 08:12 UTC, apeltzer commented
@nf-core-bot fix linting pretty please

2024-01-18 08:12 UTC, christopher-mohr approved these changes

2024-01-18 08:19 UTC, christopher-mohr approved these changes

2024-01-18 09:07 UTC, maxulysse approved these changes

2024-01-18 10:52 UTC, merged