PR for patch release
nf-core/nanostring pull request #75
Opened 2024-08-16 09:38 UTC by apeltzer

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/nanostring/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/nanostring _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-08-22 11:26 UTC, christopher-mohr requested changes
I will continue later with the rest.

2024-08-22 11:26 UTC, christopher-mohr commented on CHANGELOG.md
> +## v1.2.2 - Nanometre patch
Don't forget to add the date before release

2024-08-26 09:39 UTC, christopher-mohr commented on nextflow.config
> +    // Config options
duplicated

2024-08-26 12:36 UTC, christopher-mohr approved these changes
LGTM

2024-08-27 00:16 UTC, charles-plessy requested changes
Overall it looks good to me but I note that you have not changed the version number in |<https://github.com/nf-core/nanostring/blob/dev/assets/nf-core_nanostring_tubemap.png>… maybe it is better to do that before merging the PR? (I also note a typo after "Complex" that you can fix at the same time.)
![image](https://github.com/user-attachments/assets/0823d45c-a3fe-4b66-923c-a160cc6a4727)

2024-08-27 06:32 UTC, christopher-mohr commented
> Overall it looks good to me but I note that you have not changed the version number in |https://github.com/nf-core/nanostring/blob/dev/assets/nf-core_nanostring_tubemap.png… maybe it is better to do that before merging the PR? (I also note a typo after "Complex" that you can fix at the same time.) ![image](https://private-user-images.githubusercontent.com/1834905/361610091-0823d45c-a3fe-4b66-923c-a160cc6a4727.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDA1NDYsIm5iZiI6MTcyNDc0MDI0NiwicGF0aCI6Ii8xODM0OTA1LzM2MTYxMDA5MS0wODIzZDQ1Yy1hM2ZlLTRiNjYtOTIzYy1hMTYwY2M2YTQ3MjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjdUMDYzMDQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2E2NDkxNTEwMGNlOTk0MThhMTI1ZjBhM2VmN2I4YjA0N2Q1NTI0MmJjMmJmNGYxNDg5OTIxMzU5ZWY3ODViYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BoJ9MahnuDcUA1c-yBP3rfK9XkviUMb3pWk22tVf-WY)

well spotted :) thank you!

2024-08-27 08:52 UTC, charles-plessy approved these changes
Looks good !

2024-08-27 08:52 UTC, merged